export interface SpecialEffect {
  kind: 'revive';
}

export enum ItemType {
  Food = 'food',
  Toy = 'toy',
  Potion = 'potion',
  Special = 'special',
}
export type ItemRarity = 'common' | 'rare' | 'epic' | 'legendary';

export class ItemConfig {
  constructor(
    public readonly imageId: number,
    public readonly type: ItemType,
    public readonly rarity: ItemRarity,
    public readonly price: number,
    public readonly recoverHealth: number,
    public readonly recoverEnergy: number,
    public readonly addFriendship: number,
    public readonly specialEffect?: SpecialEffect,
  ) {}
}

export const ITEMS_CONFIG = {
  APPLE: new ItemConfig(1, ItemType.Food, 'common', 20, 10, 5, 0),
  BREAD: new ItemConfig(2, ItemType.Food, 'common', 20, 10, 5, 0),
  CARROT: new ItemConfig(3, ItemType.Food, 'common', 20, 10, 5, 0),
  COOKIES: new ItemConfig(4, ItemType.Food, 'common', 20, 10, 5, 0),
  JUICE: new ItemConfig(5, ItemType.Food, 'common', 20, 10, 5, 0),
  SUSHI: new ItemConfig(6, ItemType.Food, 'rare', 30, 20, 10, 0),
  PASTA: new ItemConfig(7, ItemType.Food, 'rare', 30, 20, 10, 0),
  BURRITO: new ItemConfig(8, ItemType.Food, 'rare', 30, 20, 10, 0),
  SALAD: new ItemConfig(9, ItemType.Food, 'rare', 30, 20, 10, 0),
  SMOOTHIE: new ItemConfig(10, ItemType.Food, 'rare', 30, 20, 10, 0),
  STEAK: new ItemConfig(11, ItemType.Food, 'epic', 40, 30, 15, 0),
  RAMEN: new ItemConfig(12, ItemType.Food, 'epic', 40, 30, 15, 0),
  PIE: new ItemConfig(13, ItemType.Food, 'epic', 40, 30, 15, 0),
  CURRY: new ItemConfig(14, ItemType.Food, 'epic', 40, 30, 15, 0),
  PANCAKES: new ItemConfig(15, ItemType.Food, 'epic', 40, 30, 15, 0),
  GOLDEN_APPLE: new ItemConfig(16, ItemType.Food, 'legendary', 50, 40, 20, 0),
  DRAGON_FRUIT: new ItemConfig(17, ItemType.Food, 'legendary', 50, 40, 20, 0),
  TRUFFLE: new ItemConfig(18, ItemType.Food, 'legendary', 50, 40, 20, 0),
  TART: new ItemConfig(19, ItemType.Food, 'legendary', 50, 40, 20, 0),
  UNICORN_CAKE: new ItemConfig(20, ItemType.Food, 'legendary', 50, 40, 20, 0),
  SANDWICH: new ItemConfig(21, ItemType.Food, 'common', 20, 10, 5, 0),
  SOUP: new ItemConfig(22, ItemType.Food, 'common', 20, 10, 5, 0),
  ICE_CREAM_CONE: new ItemConfig(23, ItemType.Food, 'rare', 30, 20, 10, 0),
  FRUIT_BOWL: new ItemConfig(24, ItemType.Food, 'rare', 30, 20, 10, 0),
  TACO_PLATE: new ItemConfig(25, ItemType.Food, 'epic', 40, 30, 15, 0),
  CHEESE_FONDUE: new ItemConfig(26, ItemType.Food, 'epic', 40, 30, 15, 0),
  PHOENIX_FEAST: new ItemConfig(27, ItemType.Food, 'legendary', 50, 40, 20, 0),
  CELESTIAL_DESSERT: new ItemConfig(
    28,
    ItemType.Food,
    'legendary',
    50,
    40,
    20,
    0,
  ),
  GALAXY_PIZZA: new ItemConfig(29, ItemType.Food, 'legendary', 50, 40, 20, 0),
  MERMAID_SMOOTHIE: new ItemConfig(
    30,
    ItemType.Food,
    'legendary',
    50,
    40,
    20,
    0,
  ),
  BALL: new ItemConfig(1, ItemType.Toy, 'common', 20, 0, 0, 10),
  ROPE: new ItemConfig(2, ItemType.Toy, 'common', 20, 0, 0, 10),
  STICK: new ItemConfig(3, ItemType.Toy, 'common', 20, 0, 0, 10),
  SMALL_PLUSH: new ItemConfig(4, ItemType.Toy, 'common', 20, 0, 0, 10),
  RATTLE: new ItemConfig(5, ItemType.Toy, 'common', 20, 0, 0, 10),
  FRISBEE: new ItemConfig(6, ItemType.Toy, 'rare', 30, 0, 0, 20),
  YOYO: new ItemConfig(7, ItemType.Toy, 'rare', 30, 0, 0, 20),
  SQUEAK_DUCK: new ItemConfig(8, ItemType.Toy, 'rare', 30, 0, 0, 20),
  CUBE_PUZZLE: new ItemConfig(9, ItemType.Toy, 'rare', 30, 0, 0, 20),
  CRINKLE_TUNNEL: new ItemConfig(10, ItemType.Toy, 'rare', 30, 0, 0, 20),
  LASER_POINTER: new ItemConfig(11, ItemType.Toy, 'epic', 40, 0, 0, 30),
  ROBOT_MOUSE: new ItemConfig(12, ItemType.Toy, 'epic', 40, 0, 0, 30),
  GIANT_PLUSH: new ItemConfig(13, ItemType.Toy, 'epic', 40, 0, 0, 30),
  BUBBLE_MACHINE: new ItemConfig(14, ItemType.Toy, 'epic', 40, 0, 0, 30),
  MINI_TRAMPOLINE: new ItemConfig(15, ItemType.Toy, 'epic', 40, 0, 0, 30),
  HOLO_BALL: new ItemConfig(16, ItemType.Toy, 'legendary', 50, 0, 0, 40),
  DRONE_BIRD: new ItemConfig(17, ItemType.Toy, 'legendary', 50, 0, 0, 40),
  MAGIC_WAND: new ItemConfig(18, ItemType.Toy, 'legendary', 50, 0, 0, 40),
  VR_HEADSET: new ItemConfig(19, ItemType.Toy, 'legendary', 50, 0, 0, 40),
  UNICORN_PLUSH: new ItemConfig(20, ItemType.Toy, 'legendary', 50, 0, 0, 40),
  POTION_HEALTH_C: new ItemConfig(1, ItemType.Potion, 'common', 30, 40, 0, 0),
  POTION_ENERGY_C: new ItemConfig(2, ItemType.Potion, 'common', 30, 0, 40, 0),
  POTION_HEALTH_R: new ItemConfig(3, ItemType.Potion, 'rare', 40, 60, 0, 0),
  POTION_ENERGY_R: new ItemConfig(4, ItemType.Potion, 'rare', 40, 0, 60, 0),
  POTION_HEALTH_E: new ItemConfig(5, ItemType.Potion, 'epic', 50, 80, 0, 0),
  POTION_ENERGY_E: new ItemConfig(6, ItemType.Potion, 'epic', 50, 0, 80, 0),
  POTION_HEALTH_L: new ItemConfig(
    7,
    ItemType.Potion,
    'legendary',
    60,
    100,
    0,
    0,
  ),
  POTION_ENERGY_L: new ItemConfig(
    8,
    ItemType.Potion,
    'legendary',
    60,
    0,
    100,
    0,
  ),
  PHOENIX_FEATHER: new ItemConfig(
    1,
    ItemType.Special,
    'legendary',
    120,
    0,
    0,
    0,
    {
      kind: 'revive',
    },
  ),
};
export const ITEMS_KEYS = Object.keys(ITEMS_CONFIG) as ItemsKey[];
export type ItemsKey = keyof typeof ITEMS_CONFIG;
