export const backgroundSounds = {
  sounds: [
    {
      id: "rain",
      label: "Rain",
      icon: "🌧️",
      locked: false,
      file: require("@/assets/sounds/rain.mp3"),
    },
    {
      id: "fire",
      label: "Fire",
      icon: "🔥",
      locked: false,
      file: require("@/assets/sounds/fire.mp3"),
    },
    {
      id: "wind",
      label: "Wind",
      icon: "💨",
      locked: false,
      file: require("@/assets/sounds/wind.mp3"),
    },
    {
      id: "ocean",
      label: "Ocean",
      icon: "🌊",
      locked: false,
      file: require("@/assets/sounds/ocean.mp3"),
    },
    {
      id: "thunder",
      label: "Thunder",
      icon: "⚡",
      locked: false,
      file: require("@/assets/sounds/rain.mp3"),
    },
    {
      id: "river",
      label: "River",
      icon: "💧",
      locked: false,
      file: require("@/assets/sounds/river.mp3"),
    },
    {
      id: "forest_rain",
      label: "Forest Rain",
      icon: "🌲",
      locked: true,
      file: require("@/assets/sounds/forest-rain.mp3"),
    },
    {
      id: "birds",
      label: "Birds",
      icon: "🐦",
      locked: true,
      file: require("@/assets/sounds/birds.mp3"),
    },
    {
      id: "crickets",
      label: "Crickets",
      icon: "🦗",
      locked: true,
      file: require("@/assets/sounds/crickets.mp3"),
    },
  ],
  mixes: [
    {
      id: "summer_wind",
      label: "Summer Wind",
      iconSequence: ["⚡", "🌧️", "💧", "🦗"],
      locked: false,
      file: require("@/assets/sounds/forest-rain.mp3"),
    },
  ],
  music: [
    {
      id: "calm_piano",
      label: "Calm Piano",
      icon: "🎹",
      locked: false,
      file: require("@/assets/sounds/rain.mp3"),
    },
    {
      id: "lofi_beats",
      label: "Lo-Fi Beats",
      icon: "🎧",
      locked: false,
      file: require("@/assets/sounds/rain.mp3"),
    },
    {
      id: "ambient_guitar",
      label: "Ambient Guitar",
      icon: "🎸",
      locked: false,
      file: require("@/assets/sounds/rain.mp3"),
    },
    {
      id: "nature_strings",
      label: "Nature Strings",
      icon: "🎻",
      locked: false,
      file: require("@/assets/sounds/rain.mp3"),
    },
    {
      id: "soft_drums",
      label: "Soft Drums",
      icon: "🥁",
      locked: false,
      file: require("@/assets/sounds/rain.mp3"),
    },
    {
      id: "deep_synths",
      label: "Deep Synths",
      icon: "🎛️",
      locked: false,
      file: require("@/assets/sounds/rain.mp3"),
    },
    {
      id: "zen_flute",
      label: "Zen Flute",
      icon: "🎷",
      locked: false,
      file: require("@/assets/sounds/rain.mp3"),
    },
    {
      id: "forest_chants",
      label: "Forest Chants",
      icon: "🪘",
      locked: false,
      file: require("@/assets/sounds/rain.mp3"),
    },
    {
      id: "warm_strings",
      label: "Warm Strings",
      icon: "🎼",
      locked: false,
      file: require("@/assets/sounds/rain.mp3"),
    },
  ],
};

export type TabID = "sounds" | "music" | "mixes";
