export const PetsList = [
  { id: 1, image: require("@/assets/images/pets/1.png") },
  { id: 2, image: require("@/assets/images/pets/2.png") },
  { id: 3, image: require("@/assets/images/pets/3.png") },
  { id: 4, image: require("@/assets/images/pets/4.png") },
  { id: 5, image: require("@/assets/images/pets/5.png") },
  { id: 6, image: require("@/assets/images/pets/6.png") },
  {
    id: 7,
    image: require("@/assets/images/pets/7.png"),
    height: 148,
    padding: 12,
  },
  {
    id: 8,
    image: require("@/assets/images/pets/8.png"),
    height: 148,
    padding: 12,
  },
  { id: 9, image: require("@/assets/images/pets/9.png") },
  {
    id: 10,
    image: require("@/assets/images/pets/10.png"),
    height: 148,
    padding: 12,
  },
  {
    id: 11,
    image: require("@/assets/images/pets/11.png"),
    height: 148,
    padding: 12,
  },
  {
    id: 12,
    image: require("@/assets/images/pets/12.png"),
    height: 148,
    padding: 12,
  },
  { id: 13, image: require("@/assets/images/pets/13.png") },
  { id: 14, image: require("@/assets/images/pets/14.png") },
  { id: 15, image: require("@/assets/images/pets/15.png") },
  {
    id: 16,
    image: require("@/assets/images/pets/16.png"),
    height: 148,
    padding: 12,
  },
  { id: 17, image: require("@/assets/images/pets/17.png") },
  { id: 18, image: require("@/assets/images/pets/18.png") },
  { id: 19, image: require("@/assets/images/pets/19.png") },
  { id: 20, image: require("@/assets/images/pets/20.png") },
  { id: 21, image: require("@/assets/images/pets/21.png") },
  { id: 22, image: require("@/assets/images/pets/22.png") },
  { id: 23, image: require("@/assets/images/pets/23.png") },
  { id: 24, image: require("@/assets/images/pets/24.png") },
  { id: 25, image: require("@/assets/images/pets/25.png") },
  { id: 26, image: require("@/assets/images/pets/26.png") },
  { id: 27, image: require("@/assets/images/pets/27.png") },
  {
    id: 28,
    image: require("@/assets/images/pets/28.png"),
    height: 148,
    padding: 12,
  },
  { id: 29, image: require("@/assets/images/pets/29.png") },
  { id: 30, image: require("@/assets/images/pets/30.png") },
  { id: 31, image: require("@/assets/images/pets/31.png") },
  { id: 32, image: require("@/assets/images/pets/32.png") },
  { id: 33, image: require("@/assets/images/pets/33.png") },
  { id: 34, image: require("@/assets/images/pets/34.png") },
  { id: 35, image: require("@/assets/images/pets/35.png") },
  { id: 36, image: require("@/assets/images/pets/36.png") },
  { id: 37, image: require("@/assets/images/pets/37.png") },
  { id: 38, image: require("@/assets/images/pets/38.png") },
  { id: 39, image: require("@/assets/images/pets/39.png") },
  {
    id: 40,
    image: require("@/assets/images/pets/40.png"),
    height: 148,
    padding: 12,
  },
];
