export class AchievementConfig {
  constructor(
    public readonly id: string,
    public readonly title: string,
    public readonly description: string,
    public readonly trigger: string,
    public readonly threshold: number,
    public readonly icon: string,
  ) {}
}

export const ACHIEVEMENTS_CONFIG = {
  first_session: new AchievementConfig(
    'first_session',
    'First Victory',
    'Complete your first session',
    'sessionCompleted',
    1,
    '🥇',
  ),
  session_10: new AchievementConfig(
    'session_10',
    'Building the Habit',
    'Complete 10 sessions',
    'sessionCompleted',
    10,
    '🧱',
  ),
  session_30: new AchievementConfig(
    'session_30',
    'Zen Master',
    'Complete 30 sessions',
    'sessionCompleted',
    30,
    '🌿',
  ),
  streak_3: new AchievementConfig(
    'streak_3',
    'Small Flame',
    'Reach a 3-day streak',
    'streakUpdated',
    3,
    '🔥',
  ),
  streak_7: new AchievementConfig(
    'streak_7',
    'Consistency Hero',
    'Reach a 7-day streak',
    'streakUpdated',
    7,
    '🔥7',
  ),
  streak_30: new AchievementConfig(
    'streak_30',
    'Legendary Streak',
    'Reach a 30-day streak',
    'streakUpdated',
    30,
    '🧨',
  ),
  note_1: new AchievementConfig(
    'note_1',
    'Memory Maker',
    'Write your first note',
    'noteCreated',
    1,
    '🧠',
  ),
  note_10: new AchievementConfig(
    'note_10',
    'Reflective Soul',
    'Write 10 notes',
    'noteCreated',
    10,
    '📝',
  ),
  task_5: new AchievementConfig(
    'task_5',
    'Getting Things Done',
    'Complete 5 tasks',
    'taskCompleted',
    5,
    '✅',
  ),
  task_20: new AchievementConfig(
    'task_20',
    'Productivity Machine',
    'Complete 20 tasks',
    'taskCompleted',
    20,
    '💼',
  ),
  egg_1: new AchievementConfig(
    'egg_1',
    'First Egg',
    'Get your first egg',
    'eggObtained',
    1,
    '🥚',
  ),
  pet_1: new AchievementConfig(
    'pet_1',
    'First Pet',
    'Hatch your first pet',
    'petHatched',
    1,
    '🐣',
  ),
  pet_5: new AchievementConfig(
    'pet_5',
    'Pet Collector',
    'Hatch 5 pets',
    'petHatched',
    5,
    '🐾',
  ),
  level_5: new AchievementConfig(
    'level_5',
    'Level Up!',
    'Reach level 5',
    'userLevelUp',
    5,
    '⭐',
  ),
  level_10: new AchievementConfig(
    'level_10',
    'Veteran',
    'Reach level 10',
    'userLevelUp',
    10,
    '🌟',
  ),
  first_fail: new AchievementConfig(
    'first_fail',
    'Comeback Kid',
    'Fail once and try again',
    'sessionFailedThenCompleted',
    1,
    '💪',
  ),
};

export type AchievementsKey = keyof typeof ACHIEVEMENTS_CONFIG;
