name: Build and deploy
on:
  workflow_dispatch:
  push:
    branches: [dev]
jobs:
  deploy:
    uses: ./.github/workflows/deploy-helper.yml
    with:
        target_env: STAGE
    secrets: inherit
      
